name: 'Repository Maintenance'

on:
  schedule:
    - cron: '3 3 * * 6'

jobs:
  action:
    name: 'Repository Maintenance'
    uses: mprins/.github/.github/workflows/maintenance.yml@main
    with:
        issue-inactive-days: '90'
        pr-inactive-days: '60'
